# Generated by Django 5.2.8 on 2026-04-13 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, help_text='Optional profile picture for the portal header (JPG, PNG, GIF, or WebP).', null=True, upload_to='web_ui_app/avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'gif', 'webp'))]),
        ),
    ]
